version: '3.7'
services:
  redis:
    container_name: redis
    hostname: redis
    image: sameersbn/redis:4.0.9-2
    command: --port 6380
    ports:
      - "6380:6380"
    expose:
      - "6380"
    volumes:
      - type: volume
        source: redis-data
        target: /data
    restart: always
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6380
    ports:
      - "8082:8081"

  mongo:
    container_name: mongo
    image: mongo:4.0-xenial
    volumes:
      - ./.data:/data/db
    environment:
      MONGO_INITDB_DATABASE: sales
    ports:
      - 27017:27017

volumes:
  redis-data: {}
