---
apiVersion: v1
kind: Service
metadata:
  name: sales-middleware-cap
  labels:
    app: sales-middleware-cap
    service: sales-middleware
spec:
  ports:
  - port: 80
    targetPort: 4004
    protocol: TCP
    name: http
  selector:
    app: sales-middleware-cap
---
apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  labels:
    app: sales-middleware-cap
  name: sales-middleware-cap
spec:
  service:
    host: sales-middleware-cap
    name: sales-middleware-cap
    port: 80
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
    - path: /.*
      methods: ["GET", "PUT", "POST", "HEAD", "PATCH", "DELETE" ]
      accessStrategies:
        - handler: noop
      mutators: []
