---
apiVersion: v1
kind: Service
metadata:
  name: c4c-events-consumer
  labels:
    app: c4c-events-consumer
    service: c4c-events-consumer
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: c4c-events-consumer
